name       : python-pako
version    : 0.3.1
release    : 4
source     :
    - https://pypi.io/packages/source/p/pako/pako-0.3.1.tar.gz : c033a073bb818ca336ae1fccba2655bd60dfe77744f85d4517abd3160d72231f
license    : Apache-2.0
component  : programming.python
summary    : The universal package manager library
description: |
    pako translates pako commands into OS's package manager commands.
builddeps  :
    - python-appdirs
rundeps    :
    - python-appdirs
build      : |
    %python3_setup
install    : |
    %python3_install
    rm -rf $installdir/usr/pako
check      : |
    %python3_test
